name: Build and Publish storybook to GitHub Pages

on:
  push:
    branches:
      - "main"
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v3
    
    - name: Install Dependencies
      run: npm run npm-install-storybook

    - id: build-publish
      name: Publish to GitHub Pages
      uses: bitovi/github-actions-storybook-to-github-pages@v1.0.0
      with:
        path: test/storybook/dist
        build_command: npm run build-storybook
